### PR TITLE
Enhance code maintainability 

### PR DESCRIPTION
**Pull request by hamzahamidi**

### CODE REVIEW

**Comment by SamuelMarks** [comment]
```
Angular6-json-schema-form/e2e/src/app.po.ts
    Error:Error:line (4)TS4053: Return type of public method from exported class has or is using name 'promise.Promise' from external module "Angular6-json-schema-form/node_modules/@types/selenium-webdriver/index" but cannot be named.
    Error:Error:line (8)TS4053: Return type of public method from exported class has or is using name 'promise.Promise' from external module "Angular6-json-schema-form/node_modules/@types/selenium-webdriver/index" but cannot be named.
Angular6-json-schema-form/src/app/demo.component.ts
    Error:Error:line (8)TS2307: Cannot find module 'angular6-json-schema-form'.
Angular6-json-schema-form/src/app/demo.module.ts
    Error:Error:line (32)TS2307: Cannot find module 'angular6-json-schema-form'.
```

**Comment by hamzahamidi** [comment]
Thank you for your review @SamuelMarks . Can you please share with us the steps to reproduce this error? Thank you

**Comment by SamuelMarks** [comment]
Usually I setup my IDE with the root `tsconfig.json` to 'Compile TypeScript'. But here's a shot from the CLI:
```
$ git clone https://github.com/hamzahamidi/Angular6-json-schema-form
Cloning into 'Angular6-json-schema-form'...
remote: Counting objects: 867, done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 867 (delta 40), reused 60 (delta 29), pack-reused 764
Receiving objects: 100% (867/867), 2.66 MiB | 1.15 MiB/s, done.
Resolving deltas: 100% (420/420), done.
$ cd Angular6-json-schema-form
$ yarn
yarn install v1.9.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 📃  Building fresh packages...
✨  Done in 17.72s.
$ tsc
src/app/demo.component.ts:8:29 - error TS2307: Cannot find module 'angular6-json-schema-form'.

8 import { JsonPointer } from 'angular6-json-schema-form';
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/app/demo.module.ts:32:8 - error TS2307: Cannot find module 'angular6-json-schema-form'.

32 } from 'angular6-json-schema-form';
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by hamzahamidi** [comment]
@SamuelMarks  Thank you for your quick reply. Try running `$ yarn buildlib` to generate the bundles of the library.

**Comment by SamuelMarks** [comment]
Hmm, that worked.

Were you able to replicate:
> Error:Error:line (4)TS4053: Return type of public method from exported class has or is using name 'promise.Promise' from external module "Angular6-json-schema-form/node_modules/@types/selenium-webdriver/index" but cannot be named.

**Comment by hamzahamidi** [comment]
@SamuelMarks Glad it solved your first issue. For the second one I can't seem to reproduce it.

**Pull request merged**
