### PR TITLE
Fix for date picker - Date is a day less than the picked date from the date picker form control

### PR DESCRIPTION
**Pull request by knaveen01**
The date picker form control has an issue with selected date. When user picks a date, the stringified date (which is converted by using date.toISOString()) is a day less than what the user has picked in date picker. It can still be recreated in the demo site (https://hamidihamza.com/Angular6-json-schema-form/)

Step to reproduce -

1. Open the demo site (https://hamidihamza.com/Angular6-json-schema-form/)
2. Find birthday date picker control -> chose a different birth data, say - 4th Feb 2019.
3. On form change / submit, you can see in the json data, the birth date is stored as 3rd Feb 2019.

Reason - 

The issue is in string to date conversion logic in date.functions.ts (shared directory) file. i.e. stringToDate()

The existing logic fails to capture the time difference in the GMT! consider the below example,

var date1 = new Date('2019,02,04'); // or ==> var date1 = new Date('2019/02/04');
console.log(date1.toString());
console.log(date1.toISOString());

output will be 

01 > "Mon Feb 04 2019 00:00:00 GMT+0530 (India Standard Time)"
02 > "2019-02-03T18:30:00.000Z"

Line number 01 shows, 5.30 hours is not considered as part of stringified date therefore ISO strigified date shows one day less in the output!!

consider second exapmple which illustrates the conrreect usage.

var date2 = new Date('2019-02-04');
console.log(date2.toString());
console.log(date2.toISOString());

output,

01 > "Mon Feb 04 2019 05:30:00 GMT+0530 (India Standard Time)"
02 > "2019-02-04T00:00:00.000Z"

which is 100%, it shows 5.30 hours difference and the date is also correct.

### CODE REVIEW

**Comment by hamzahamidi** [comment]
@knaveen01  Thank you for your PR. 
The date is one day behind when giving a default value to date & only in material case.

**Comment by hamzahamidi** [comment]
#71

**Comment by knaveen01** [comment]
@hamzahamidi ,Thanks for the update. 
But, unfortunately, it doesn't work for PST (UTC-08:00) US & Canada. Can you please check. @ https://hamidihamza.com/Angular6-json-schema-form/

**Comment by hamzahamidi** [comment]
@knaveen01 I can't reproduce this issue. Can you give me more information on how to reproduce it? that is only concern initial value? Meterial bootstrap ...? Which timezone is affected?

**Comment by knaveen01** [comment]
@hamzahamidi, 
Yes, it's with material framework (bootstrap and other frameworks work fine). Issue is still there, with default date value and as we as on date pick also.

To reproduce the issue, change your machine timezone to PST and test for the issue before 8 AM PST.

**Comment by knaveen01** [comment]
I fixed the issue by making below changes  (in material-datepicker.component.ts) on top of your #71 fix

**On Init**

Replacing 
`if (this.controlValue) { this.setDate(dateToString(new Date(this.controlValue))); }` 

by 
`if (this.controlValue) { let dateStr = this.controlValue.slice(0,10);
    this.jsf.updateValue(this,dateStr +"T00:00:00");
}`

**& On update** 

Replacing,
`if (event.value) { this.setDate(dateToString(event.value)); }`

by 

`if (event.value) {
 let dateStr = dateToString(event.value);
    this.jsf.updateValue(this,dateStr +"T00:00:00");
}`

The idea is we need to maintain the dates in standard date time format.

**Comment by hamzahamidi** [comment]
If going by UTC timezone did solve this issue. Why not just add **.toUTCString()** instead of slice. 
If so, can you please make a clean PR with these changes?

```javascript
if (this.controlValue) { this.setDate(dateToString(new Date(this.controlValue).toUTCString())); }
```
&&
```javascript
if (event.value) { this.setDate(dateToString(event.value.toUTCString())); }
```

**Comment by knaveen01** [comment]
@hamzahamidi , The literal code change suggested by you doesn't work. 
If you are suggesting to use UTC date string, please have a  look at below  output,

`var event = new Date("2019-02-07");
console.log(event.toUTCString());
console.log(event.toISOString());`

 Output - 
 
`Thu, 07 Feb 2019 00:00:00 GMT \n
 2019-02-07T00:00:00.000Z`

If you see, ISO format is what we want not UTC format. 
But, even with ISO formatted date string, once we do new Date (<iso_formatted_date_string>) and set the value to the control, It works (as before) in GTM+\<HOUR\>time zones but it still fails in GMT-\<HOUR\> time zones.

I am still going with my previous solution. Once I come up with clean fix, will send a PR

**Comment by knaveen01** [comment]
I am using the above mentioned fix (by neutralizing the time zone hours differences), works fine in all the time zones. Please review the PR and merge if it's fine.

**Comment by hamzahamidi** [comment]
#98

**Pull request merged**
